### PR TITLE
fully implemented urlencoded jsessionid

### PR DESCRIPTION
**Pull request by San7o**
Every link, button and fetch now adds the jsessionid token. Despite this, some pages like Evento and visualizzaProfili are not working, I'm trying my best debugging this issue but this might be a tomcat's issue. It's absurd that the admin filter passes, the profile page works, the eventi page works but those two are not.

### CODE REVIEW

**Comment by San7o** [comment]
Side note: we are very fortunate since the first servlet was made with `getRequestDispatcher(...).forward(req, res)` and all the other servlets used this as a reference. This is the right function to call for setting the cookies in the url, otherwise we would have had to change all the servlers

**Comment by San7o** [comment]
This makes no sense. We are passing the jsessionid in the url and sometimes it's working and sometimes not. We tried though. Apparently it's a problem only with AJAJ fetches, while servlets are working perfectly

**Comment by San7o** [comment]
Might be relevant:
https://answers.axonivy.com/questions/4032/rest-api-and-jsessionid

**Review by Qw3rty26 — APPROVED** [review]
LGTM

**Pull request merged**
